export PATH="/usr/local/bin/ctags:$PATH"
export PATH="/usr/local/opt/gnupg@2.1/bin:$PATH"
export PATH="$HOME/.asdf/bin:$HOME/.asdf/shims:$PATH"
export PATH="$HOME/repos/dotfiles/bin:$PATH"
export PATH="$HOME/.emacs.d/bin:$PATH"
export PATH="$HOME/elixir-ls/release:$PATH"
